source 'https://rubygems.org'

gem 'rails', '6.1.7.3'
gem 'bcrypt',         '3.1.7'
gem 'bootstrap-sass', '3.4.0'
gem 'sass-rails', '6.0.0'
gem 'uglifier', '2.7.2'
gem 'coffee-rails', '4.2.2'
gem 'jquery-rails', '4.4.0'
gem 'turbolinks', '5.0.0'
gem 'jbuilder', '2.6.4'
gem 'sdoc', '1.0.0', group: :doc

group :development, :test do
  gem 'sqlite3',     '1.3.9'
  gem 'byebug',      '3.4.0'
  gem 'web-console', '2.1.3'
  gem 'spring',      '1.1.3'
end

group :test do
  gem 'minitest-reporters', '1.0.5'
  gem 'mini_backtrace',     '0.1.3'
  gem 'guard-minitest',     '2.3.1'
end

group :production do
  gem 'pg',             '0.17.1'
  gem 'rails_12factor', '0.0.2'
  gem 'puma', '4.3.12'
end
